#
# Digital Voice Modem - Fixed Network Equipment (Router Configuration)
#
# @package DVM / Fixed Network Equipment
#

# Time in seconds between pings to peers.
pingTime: 5
# Maximum number of missable pings before a peer is considered disconnected.
maxMissedPings: 5
# Flag indicating whether or not the router should debug display all packets received.
rawPacketTrace: false
# Flag indicating whether or not the host activity log will be sent to the network.
allowActTrans: true
# Flag indicating whether or not the host diagnostic log will be sent to the network.
allowDiagTrans: true

#
monitorServerPort: 5555

# Global activity log filename.
activityLogFile: activity_log.log
# Full path for the directory to store diagnostic logs captured from peers.
diagLogPath: .

# Full path to the routing rules file.
routingRulesFile: routing_rules.yml
# Amount of time between updates of routing rules file. (minutes)
routingRuleUpdateTime: 1

#
# Logging Configuration
#   Logging Levels:
#     1 - Debug
#     2 - Message
#     3 - Informational
#     4 - Warning
#     5 - Error
#     6 - Fatal
#
log:
    # Console display logging level (used when in foreground).
    displayLevel: 1
    # File logging level.
    fileLevel: 1
    # Full path for the directory to store the log files.
    filePath: .
    # Log filename prefix.
    fileRoot: fnerouter

#
# Radio ID ACL Files
#
rids:
    # Full path for the directory containing the radio ID YAML files.
    path: .
    # Filename for the whitelisted radio IDs YAML.
    whitelistRIDFile: whitelist_rids.yml
    # Filename for the blacklisted radio IDs YAML.
    blacklistRIDFile: blacklist_rids.yml

#
# Master Instances
#
masters:
      # Textual Name
    - name: SKYNET
      # Flag indicating whether or not the master is enabled.
      enabled: true
      #
      repeat: true
      # Hostname/IP address to listen on (blank for all).
      address:
      # Port number to listen on.
      port: 62031
      # FNE access password.
      passphrase: RPT1234
      #
      groupHangtime: 5
      # Network Peer ID
      peerId: 9000100

#
# Peer Instances
#
peers:
      # Textual Name
    - name: PARROT
      # Flag indicating whether or not the master is enabled.
      enabled: true
      # Hostname/IP address to listen on (blank for all).
      address: 127.0.0.1
      # Port number to listen on.
      port: 32091
      # Master Hostname/IP address to connect to.
      masterAddress: 127.0.0.1
      # Port number to connect with.
      masterPort: 32090
      # FNE access password.
      passphrase: RPT1234
      # Textual identity of this peer.
      identity: PARROT
      # Network Peer ID
      peerId: 9000990

      #
      rxFrequency: 0
      #
      txFrequency: 0
      #
      latitude: 0.0
      #
      longitude: 0.0
      #
      location: Anywhere, USA
