#
# Digital Voice Modem - Fixed Network Equipment (Parrot Configuration)
#
# @package DVM / Fixed Network Equipment
#

# Time in seconds between pings to peers.
pingTime: 5
# Maximum number of missable pings before a peer is considered disconnected.
maxMissedPings: 5
# Flag indicating whether or not the router should debug display all packets received.
rawPacketTrace: false

#
# Logging Configuration
#   Logging Levels:
#     1 - Debug
#     2 - Message
#     3 - Informational
#     4 - Warning
#     5 - Error
#     6 - Fatal
#
log:
    # Console display logging level (used when in foreground).
    displayLevel: 1
    # File logging level.
    fileLevel: 1
    # Full path for the directory to store the log files.
    filePath: .
    # Log filename prefix.
    fileRoot: fneparrot

#
# Master Instances
#
masters:
      # Textual Name
    - name: PARROT
      # Flag indicating whether or not the master is enabled.
      enabled: true
      #
      repeat: true
      # Hostname/IP address to listen on (blank for all).
      address:
      # Port number to listen on.
      port: 32090
      # FNE access password.
      passphrase: RPT1234
      #
      groupHangtime: 5
      # Network Peer ID
      peerId: 9000990
